### ISSUE TITLE
Feat: Designer la page des Classifier 

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#17]
## Suggested solution

Pour le moment, la page liée au classifier contient uniquement la timeline.

Dans l'idée il faudrait ajouter un header regroupant plusieurs informations 

## Template

![Image](https://user-images.githubusercontent.com/44176707/196003844-8315bd7a-997b-4eb7-9e54-b08500648b43.png)

## Todo

- [x] Regarder les designs possibles 
- [ ] ~~Ajouter le header uniquement pour les topic~~
- [ ] ~~Ne pas afficher d'image (celle ci sera ajoutée plus tard)~~
- [x] Créer le breadcrumb en twig / scss
- [x] Ajouter une icône en premier pour les topics et les tags
   - Topic -> tag
   - Tag -> hash
