### ISSUE TITLE
Feat: Abandonner Storybook pour Histoire

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#18]
## Suggested solution

Pour le moment, les stories pour intéragir avec les composants sont gérées avec Storybook. Malheureusement, cet outil est lent, chiant configurer, ...

Pour améliorer ce processus, un changement d'outil est nécessaire. `Histoire` sera implément

## Todo

- [x] Installer la librairie
- [x] Configurer la librairie
- [x] Migrer les stories vers Histoire
