### ISSUE TITLE
Feat: Encapsuler le style du composant TimelineThread

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#19]
## Suggested solution
A l'heure actuelle, le composant TimelineThread ne permet de styliser les composant pour les events, article et moodline.
Il faudrait créer un composant pour chaque type de thread avec le style `scoped`

## Todo
- [x] Créer un composant pour chaque type
- [x] Modifier le composant TimelineWrapper
- [x] Modifier les stories correspondantes
