### ISSUE TITLE
Feat: Designer les pages pour l'authentification (login / register)

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#30]
## Suggested solution
Les pages liées générées par Symfony ne sont pas top. L'idée ici est de redesigner les pages en utilisant le style de [Notice](https://github.com/MrAnyx/Notice)

## Template
https://dribbble.com/shots/14981045-Login-Sign-in
https://dribbble.com/shots/17564792-Log-in-page-Untitled-UI

## Linked issue
#29 #28

## Todo
- [x] Créer les fichiers scss correspondants
- [x] Créer le layout pour l'authentification
- [x] Afficher les messages d'erreurs en fonction du validator
- [x] Design login page
- [ ] Design register page
