### ISSUE TITLE
Feat: Ajouter la vérification du compte par mail

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#34]
## Suggested solution

Pour améliorer la sécurité du compte, il va falloir implémenter la vérification du compte par mail.

## Todo
- [ ] S'inspirer de Notice et Email-verify-bundle
- [ ] Envoyer le mail depuis `Needlify - Noreply`
- [ ] Designer les pages de vérification
