### ISSUE TITLE
Feat: Ajouter le "mot de passe oublié"

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#35]
## Suggested solution

Dans le cas ou l'utilisateur oublié son mot de passe, il va falloirt implémenter la fonctionnalité pour réinitialiser le mot de passe.

## Todo
- [ ] S'inspirer de Notice
- [ ] Installer manuellement la version 1.10 de la librairie reset-password-bundle
- [ ] Configurer la librairie
- [ ] Designer les pages
