### ISSUE TITLE
Feat: Ajouter HTMLPurifier pour les articles et les events

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#40]
## Suggested solution

http://htmlpurifier.org/docs

## Todo
- [ ] Installer la librairie
- [ ] Configurer la librairie
- [ ] Utiliser la librairie pour les events et les articles
