### ISSUE TITLE
Feat: Mettre à jours les tests / stories

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#47]
## Suggested solution

Plusieurs classes / méthodes ne sont pour le moment pas encore testées. Il faudrait alors créer les tests associés pour ces éléments puissent être testés convenablement

## Todo
- [ ] Créer les tests manquants
- [ ] Créer les stories manquantes
- [ ] Créer les tests unitaires php manquants
