### ISSUE TITLE
Feat: Installer et configurer l'outil husky

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#50]
## Suggested solution

Husky permet de lancer des commandes personnalisées avant / après un commit. Dans notre cas, nous pourrions utiliser cet outil pour lancer les tests avant de commit et push

## Todo
- [ ] Installer la librairie
- [ ] Configurer la librairie
- [ ] Lancer les tests avant de commit
