### ISSUE TITLE
Feat: Ajouter HTMLPurifier lors de l'affichage d'un article / moodline / event

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#51]
## Suggested solution

Le purifier permet notamment de retirer les éléments html non autorisés pour ne garder que ce qui est pris en compte. Également, cela permet de supprimer les attributs qui pourraient poser problème lors du rendu de la page

## Todo
- [ ] Installer HTMLPurifier
- [ ] Configurer la librairie
- [ ] L'utiliser lors du rendu d'un article
- [ ] Utiliser lors du rendu dans la timeline (event, moodline)
