### ISSUE TITLE
Feat: Migrer les composants vue vers Symfony UX

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#52]
## Suggested solution

Actuellement, les composants vue sont trop utilisés pour du contenu très simple. L'idée serait de migrer les composants complexes vers des LiveComponents et les composants simples vers des TwigComponents

## Todo
- [ ] Migrer les composants complexes vers LiveComponents
- [ ] Migrer les composants simples vers TwigComponents
- [ ] Supprimer la logique Vue
- [ ] Supprimer les assets Vue
- [ ] Supprimer les stories Vue
- [ ] Supprimer les tests Vue
