### ISSUE TITLE
Feat: Analyse custom namer pour VichUploader

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#55]
## Suggested solution

Pour être un peu plus flexible sur le nom du fichier / dossier, il faudrait voir si c'est pertinent d'utiliser un custom namer pour les dossier / fichier

## Linked issue
#46 

## Todo
- [ ] Regarder la doc
- [ ] Analyser les points + et -
- [ ] Si c'est pertinent, déterminer le format idéal pour le fichier / dossier
