### ISSUE TITLE
Feat: Ajouter un boolean pour la licence des articles

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#56]
## Suggested solution

Pour le moment, la licence est toujours affichée, il faudrait l'afficher conditionnellement en fonction d'un paramètre

## Todo
- [x] Ajouter le nouveau champ
- [x] Créer la migration
- [x] Modifier les fixtures
- [x] Modifier le fichier twig pour prendre en compte ce nouveau champ
