### ISSUE TITLE
Feat: Implémenter ZenstruckFoundryBundle pour les fixtures

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#57]
## Suggested solution

Les factory de ce bundle permettraient de plus simplement créer des fixtures et des données fake

## Todo
- [x] Installer la librairie
- [x] Configurer la librairie
- [x] Implémenter les modifications
