### ISSUE TITLE
Feat: Designer le header

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#59]
## Suggested solution
Pour le moment, le header contient uniquement le logo avec un texte "Hello World". L'idée serait d'ajouter un dropdown custom / lien vers la connexion

## Template
S'inspirer de Notice

## Todo
- [x] Ajouter le lien vers la page de connexion
- [x] Créer le dropdown
- [x] Y mettre les liens nécessaires
