### ISSUE TITLE
Feat: Création des routes pour les Classifiers

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#6]
## Suggested solution
Ici, le but sera de simplement créer les routes qui serviront à afficher le contenu en lien avec un tag ou un topic.

## Todo
- [x] Créer les controllers correspondant `TagController` et `TopicController`
- [x] Ajouter la route pour les `tags` et les `topics`
- [x] Utiliser le ParamConverter personnalisé pour récupérer le tag ou le topic correspondant
- [x] Modifier les routes utilisées dans le composant vue pour rediriger vers la bonne route
