### ISSUE TITLE
Feat: Implémenter la sélection du type de thread

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#7]
## Suggested solution
Pour le moment, la timeline ne permet pas de sélectionner le type de thread que l'on souhaite (Article, Moodline, Event)
L'idée est d'implémenter un dropdown de manière à choisir ce que l'on souhaite afficher.

L'affichage du dropdown se fera directement dans le composant timeline grâce à la librairie [vue-tippy](https://vue-tippy.netlify.app/basic-usage/)

## Template
Dans l'idée, le design ressemblera à quelque chose comme ça :

![image](https://user-images.githubusercontent.com/44176707/194319319-239ffc07-67c7-46c1-a2cd-75130ef960eb.png)

## Todo
- [ ] Installer la librairie [vue-tippy](https://vue-tippy.netlify.app/basic-usage/)
- [ ] Ajouter le plugin pour vue (suivre la doc)
- [ ] Configurer la librairie (suivre la doc)
- [ ] Implémenter la librairie avec le choix des éléments
