### ISSUE TITLE
Feat: créer le formulaire pour la newsletter

### ISSUE THREAD

**Issue by MrAnyx** [Needlify/Needlify#74]
## Suggested solution

Rechercher une solution pour mettre la newsletter sur un autre nom de domaine ou bien rester sur needlify 

## Todo

- [x] Réutiliser le layout auth
- [x] Créer la route
- [x] Créer la gestion du formulaire
- [x] Créer la table
- [x] Créer l'entité
- [x] Créer le crud dans le dashboard
